### ISSUE TITLE
Add highlight and typo-tolerance to the search

### ISSUE THREAD

**Issue by pixelastic** [madebyform/react-parts#11]
Hello,

Thanks for building react-parts, this is a really useful tool for me. I think the search results can still be improved, by adding highlight on the matching words and auto-fixing typos (among other things).

I took the liberty of forking the code and replace the json-based search with one using [Algolia](http://algolia.com/) (which is a SaaS search engine, with the above features built-in). Full disclosure: I work at Algolia. Here is what it looks like:

![React-Parts screencast](https://raw.githubusercontent.com/pixelastic/sov/master/pull_requests/react-parts/screencast.gif)

You can test it live [here](https://afternoon-savannah-7018.herokuapp.com/native-ios) (this is hosted on an heroku free plan, so first load might be slow).

Tell me if this is something you would be interested in. If so, I'll submit a PR. We're used to giving custom and free accounts to open-source projects as a way of contributing back, so this won't cost you anything. I did those changes a few weeks ago so I did not (yet) include the latest changes to the UI you did, but I'll happily merge them back.

Looking forward to hear from you, and see if we can build something together.

**Comment by dmfrancisco** [comment]
Hello @pixelastic,

First of all thank you for using react.parts and for taking the time to contribute. I would also like to thank Algolia for supporting open source projects :+1: Although I don't find myself needing the counters or the highlighting, the fuzzy matching is definitely a big improvement.

My only concern right now is that we only deploy whenever we add new features. The data files are simply uploaded via `scp` to the servers. Can you show us your fork to understand how you're doing the indexing? Thank you again for your contribution!

**Comment by pixelastic** [comment]
Sure thing.

The code responsible for pushing data to the index is here : https://github.com/algolia/react-parts/blob/feature/algolia-search/algolia.js

It basically reads the `./components/react-web.json` and `./components/react-native-ios.json` json files and push its content to the Algolia indices (pushing all ranking-relative settings with it). To keep your search index in sync, you'll have to re-run this script everytime you update the list of plugins (I guess this will replace the `scp` command).

(Don't pay attention to the multiple commits in the repo, I'll rebase/squash that properly later).

**Comment by fbatista** [comment]
I personally like what i see in the PR. I hadn't tried Algolia in the past, but it seems pretty sweet, specially the part of not having to worry about maintaining an ElasticSearch / Solr instance, and the API is indeed friendly. :+1:

**Comment by dmfrancisco** [comment]
Hey again @pixelastic,

First of all, I'm sorry you had to do all those fixes to `fetch.js`. I did them too a long time ago but only consolidated and pushed them recently.

I like how the details related to the Algolia API are isolated in a single file. One thing I didn't understand in the new `algolia.js` script is that you push the `components/react-*.json` files instead of the `data/react-*.json` ones (that contain the metadata, such as stars).

Another thing I noticed (probably an easy fix) is with the pagination: Try to visit `/web` and go to "Next page". Now refresh the page. The results are not the same. One thing I usually do to make sure our server-side pagination works the same way as the client is to disable JavaScript in the browser.

To clarify why we have both the `components` and `data` files, I'm writing a `readme` with information about our current process (and also about our deployment strategy).

Thank you again! We really appreciate you taking the time to make React.parts better :+1:

**Comment by pixelastic** [comment]
I must confess I did not completely understood the difference between the `components` and `data` directories, so I might have copy-pasted the consolidated files (with metadata) inside the `components` directory and used that.

The fixes I did to the `fetch.js` file were mostly due to my account using two factor-authentication. In the end I disabled the 2FA before running the script and re-enabled it after :). If you did fix it on upstream I'll use your fixed version instead.

I'm glad you find this useful. I'll fix the issue you mentioned and squash/rebase all that soon. Thanks for making React.parts in the first place :)

If you want to see how it will look like from your Algolia dashboard, just create a free account and I'll give you ownership on the indices.

**Comment by dmfrancisco** [comment]
Thank you, we'll create an Algolia account later today :+1:

I hope the new `readme` will clarify why we keep the two separate folders. Your experience also reminded me that we should explain there how one can create a "Personal Access Token" in GitHub and use it as the username (with a blank password) to be granted limited read access.

We would love if you could send a simple PR with only the script and search functionality. The new release as a narrower footer, but we can add the Algolia logo to it with a link right after your PR, if you prefer. We can also add the highlighting, counters and visual changes afterwords. Let us know if that works for you!

**Comment by pixelastic** [comment]
That's perfect, I'll work on the fix/merge right now.

**Comment by pixelastic** [comment]
Until the readme is published, could help me with the order of the `npm run` commands?

Here is what I did:

``` sh
npm run download:all
npm run parse
cp ./components/react-native.json ./data
cp ./components/react-web.json ./data
npm run fetch react-native
npm run fetch react-web
```

I tried the `npm run fetch:all` commands, but they did nothing, or complained that no `json` file were found in `./data`. That's why I manually `cp` them. Am I on the right track here?

**Comment by dmfrancisco** [comment]
Generating the `data/react-*.json` files using the `components/react-*.json` files should be possible by running `npm run fetch:all`. But I just checked, and you are right, there is an issue if the files don't exist yet. Until the issue is fixed, you can:
- Download [react-web.json](https://react.parts/api/components/web) to `data/react-web.json` and [react-native.json](https://react.parts/api/components/native) to `data/react-native.json`
- Create empty json files with `[]` named `data/react-web.json` and `data/react-native.json` and then run `npm run fetch:all`

I'm sorry you are having this problem, and thanks for reporting it!

**Comment by pixelastic** [comment]
No problem, I figured this out. Thanks

**Comment by dmfrancisco** [comment]
Hello @pixelastic, our free Algolia account is associated to this address: developer@react.parts

There's now a readme.md in the master branch and the bug you reported yesterday should also be fixed. Hope this helps!

**Comment by pixelastic** [comment]
@dmfrancisco Great, I've upgraded your account to a free one with unlimited operations. Thanks for the readme, it will make things clearer for other contributors.

**Comment by dmfrancisco** [comment]
This is awesome, and it comes at a good time because we really needed a solution that scales for more than 2k components.

I'll update the `publish` script to run `algolia` and add the logo to the footer. I'm still not a fan of the highlighting. I find it too distracting and think it may be a little confusing when a record doesn't have any highlights (when what gets matched is a keyword). I also would prefer if the pagination started at 1 instead of 0. But I can make those minor changes myself.

So if you don't mind @pixelastic, I fetched and pushed your feature branch and will add those changes to the branch instead of merging the PR directly. We'll keep this PR open for now and will notify you as soon we deploy. Does that work for you?

**Comment by pixelastic** [comment]
Sure, feel free to tweak it as much as you'd like.

Regarding the highlight, maybe something acting directly on the text color instead of the background?
![image](https://cloud.githubusercontent.com/assets/283419/10342863/66a3b47c-6d1b-11e5-8812-46e35f784b68.png)

The highlight is interesting to give the user instant feedback on what he's searching, and letting him adjust his query while typing. Maybe it will become more useful when the dataset will grow. In the end, I'll let you test it and do what you think is best :)

If you could just add a link to our website on the Algolia logo that would be awesome. Keep me informed when this will be deployed :)

**Comment by dmfrancisco** [comment]
Everything seems to be working smoothly! I made some changes to the script, in order to have an index sorted by `modified`, to be used for the initial unfiltered list. Algolia's slave indices feature is really cool. I also added a `dev` index to allow us to experiment without affecting the production data.

You can check Algolia's logo here: https://new.react.parts
Again, thanks for making this possible :+1:

We'll make this available to the community within the next couple of days.

**Comment by pixelastic** [comment]
Happy to see that you started playing with it! Also, thanks for the logo, that's perfect.

Just a note though, be careful with your ranking formula. I saw that you moved the `custom` criterion in the second position. This criterion can only ever be the last of the list (meaning that all others -`words`, `proximity`, `attribute` and `exact`) will never be used. I think that is too aggressive and might not yield the most relevant results.
- `exact` is used for the typotolerance, this will rank results with no typos higher than the one with typos
- `attribute` will use the list of `attributesToIndex` you defined, giving more weight to the one on top. This lets you rank results with a match in `name` higher than the one with a match in `author` for example
- `words` is used for multiple word queries: results that match several words will be ranked higher than those that only match one
- `proximity` is used on multiple word queries as well. When searching for `audio player`, results that have `audio player` exactly will be ranked higher than the one that have `audio foo bar bar foo player`.

Disabling all those criteria will significantly impact the relevance of the search. I'd recommend reverting to the default (which is the good choice in 90% of cases). What was the use-case you were trying to solve? I'd be happy to help you with the configuration

**Comment by dmfrancisco** [comment]
Hey @pixelastic! Thank you for looking at the changes. I haven't made a lot of testing yet, but it seemed to me that the default ranking was not giving enough relevance to the stars. In theory it seems to me that:
- Exact matches must be ranked higher than partial matches
- We should give relevance to stars and downloads
- The number of occurrences of a word or position (eg: in one record `calendar` appears 3 times in description and keywords but in another record only appears once) is less relevant (in my opinion, usually not relevant at all, and that's the main difference compared to searching text in other sites)

So after trying it out a little bit it seemed that:
- Putting `custom_ranking` first was a bad idea (eg: Searching for "card" shows `react-native-carousel` at first because it has more stars). This shows that the default `typos` at first is preferable
- Putting `custom_ranking` second did better results, with matches with fewer typos on top sorted by stars and downloads

Here are some examples, left is default and right is with `custom_ranking` as second place:

<img width="1268" alt="video" src="https://cloud.githubusercontent.com/assets/212106/10389996/7eadf1a6-6e6d-11e5-946e-4fc00312cb8c.png">
<img width="1280" alt="card" src="https://cloud.githubusercontent.com/assets/212106/10390002/845058ec-6e6d-11e5-95ee-4ef3485576f1.png">
<img width="1257" alt="audio-player" src="https://cloud.githubusercontent.com/assets/212106/10390098/4d560700-6e6e-11e5-81f4-d20ad811ac58.png">

**Comment by pixelastic** [comment]
Oh, I see. Thanks for the screenshots, this makes understanding the issue much easier.

We handle the `exact` criterion a bit differently when you have only one word in the query. In that case, if a record contains an attribute that is (or an array that contains) _exactly_ what is typed, then this record is ranked higher. In your example, you have all the records that contains `video` in `keywords` ranked first (exact match, ordered by stars), then all the one that did not get an exact match (because `video` was found in the `name` or `description`), also ordered by star.

To fix that, you can either remove the `exact` criterion from your ranking formula. I would not recommend it, this will negatively impact the relevance in other use-cases. Instead, we have an _undocumented_ attribute that you can pass to your request to disable the `exact` criterion when there is only one word.

Just add to the `searchConfig` in `get-search-results.js` (don't forget to revert your ranking formula to the defaults if you do that):

``` javascript
var searchConfig = {
  [...]
  useQueryEqualsOneAttributeInRanking: 0
};
```

This should get you the same results as in your screenshots.

**Comment by dmfrancisco** [comment]
Thank you @pixelastic, that makes sense :+1: I just pushed this change.

One last thing: I've noticed that the search API fetches at most 1000 hits, which is more than enough for searches. However, when the user is not searching, she should have access to the entire catalog. I tried to use the `browse` method, but a `cursor` must be passed, which means if a user comes from an url (eg: `/web?page=60`) this wouldn't work. Since this is a fairly uncommon use-case, and the data doesn't weight that much, I [ended up doing](https://github.com/madebyform/react-parts/commit/a2b43ccbfab88ddaa400b8aa62637babdd0219bf#diff-6030d422b450243ba65aa5adbcd64ef3R63) a `browseAll` and then slicing the data on the client (or node server) on those cases. But let me know if you have any suggestion.

And that's it, thank you again! We'll deploy this weekend :tada:

**Comment by pixelastic** [comment]
Sorry I was a bit late to answer that one. As you said, the search method is limited to 1000 records, because that's enough for a search response. Nobody will skim through 1000 records manually if they have a search available to narrow down their terms. On the other hand, the `browse` method is here to let you navigate in your index (maybe for backup, stats, etc).

I think the solution you came up with is the right one. Your index is not that big, and I don't see why someone would request the 60th page anyway, so you're pretty safe.

**Comment by dmfrancisco** [comment]
Thank you for your comment :+1:

Regarding the Algolia JS Client, I may have missed something, but it was not obvious when I read the docs that the `page` param would only work in the [`browse`](https://github.com/algolia/algoliasearch-client-js#backup--retrieve-of-all-index-content) method (not `browseAll`) for the first 1000 records (after that it raises the error: _"you should pass cursor of current page to fetch next page"_). The example also uses `content.nbPages` which seemed to always be `undefined`.

The docs make it seem that the options and response are the same as the `search` method, but they don't match exactly (above the 1000 records). But I guess this is at most a documentation issue. Let me know if I should open an issue!

**Comment by pixelastic** [comment]
Oh, thanks. I'll rewrite the documentation to make that more obvious then. We'd like our documentation to be the clearest possible.

**Comment by dmfrancisco** [comment]
Hello again @pixelastic! We've been working on a [new project](https://js.coach) that has a more robust backend and that supersedes React.parts. It has been online for 2 weeks but only yesterday we [open sourced the code](https://github.com/dmfrancisco/JS.coach/tree/master/project).

Is Algolia interested in sponsoring this new project? We would love to use your search engine! If you don't mind, we would reuse this account you gave us.

**Comment by pixelastic** [comment]
Sure thing. As long as it stays non-profit and you keep our logo somewhere, we're ok :)

Good luck with the new project, and don't hesitate if you need any help.

**Comment by dmfrancisco** [comment]
Sure :smiley: Thank you Tim!
