### ISSUE TITLE
React-native package tagging issues

### ISSUE THREAD

**Issue by NishanthShankar** [madebyform/react-parts#13]
Hi,
Thanks a lot for tagging the packages. Has made life a lot easier. But I recently bumped into this issue where the tagging is slightly off.
Example in hand : https://github.com/jsierles/react-native-view-snapshot

It does not support android but is marked as for android

**Comment by dmfrancisco** [comment]
Hi @NishanthShankar,

Thank you for your feedback. Have you experienced this issue frequently?

Currently, our automated mechanism for detecting platform support is by looking at the languages in the GitHub repository. If the repo has Objective-C code, then the iOS icon is displayed. If the repo has Java code, the Android icon is shown. If there's both, we display both icons. If there's neither, it's a pure JS component (and we don't display any icon).

In the example you gave, it seems the project already has a folder with some code for Android, and that's why the tagging is off.

**Comment by NishanthShankar** [comment]
Yeah, i noticed that they added the android in example folder. But i guess that is because react-native initializes android and ios by default regardless. 
another repo I came across https://github.com/EstebanFuentealba/react-native-android-audio-streaming-aac

May be we should ask the user to tag it package.json

**Comment by dmfrancisco** [comment]
That makes sense. Some authors are already using the `ios` and `android` keywords, so I guess we should check if at least one of those two is present, and only if neither exist, trying to guess it by using the languages solution. Thank you for raising this issue @NishanthShankar :+1:

**Comment by dmfrancisco** [comment]
It's hard to get good results right now using keywords. Some older packages may be JS only and work in Android, but only have the `ios` keyword (because that's what was available at the time). For example, [react-native-localization](https://github.com/stefalda/ReactNativeLocalization) and [react-native-network-info](https://github.com/pusherman/react-native-network-info) only have the `ios` keyword but support Android.

I ended up using the keywords, but only to add platforms (not remove them), because for the current data it yielded better results. For example, [react-native-dashed-border](https://github.com/chirag04/react-native-dashed-border) and [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation) only have Objective-C code but they support Android. By using the keywords, the Android platform is correctly detected. Unfortunately, this change doesn't solve the two cases you mentioned. 

I added a note to the readme. Let's see how things evolve. After all, React Native for Android was just released last month. Thank you again for your feedback :+1:
