### ISSUE TITLE
Display monthly downloads instead of all time downloads

### ISSUE THREAD

**Issue by oblador** [madebyform/react-parts#21]
Hi and thanks for a great resource :+1: 

Showing stars and downloads for each package is a great way to quickly determine the quality of it, however I believe showing downloads per temporal unit (like monthly) better tells the story. Now since the community is quite young, having many downloads mostly mean the package has been around for a long time and not necessarily that very many use it. 

For example `rnpm` has very many downloads, but it's mostly because they inherited the name on npm (I love that project, no hate :-). Same with `react-native-versions` vs `react-native-code-push`; by total downloads code push seems about twice as popular, but in reality this month it's about five times more downloaded.

**Comment by dmfrancisco** [comment]
Hi @oblador, thank you too for all the native components you have been developing :+1:

You raise a valid point. Total number of downloads is not as useful as last month's downloads. I'm currently working on the successor of React.parts and I'll definitely make this change.

I also added a background chart that I think may help. Another thing that could be useful would be sorting by number of downloads last week/month to see what's "trending". What do you think?

<img width="780" alt="oblador" src="https://cloud.githubusercontent.com/assets/212106/12018489/579643de-ad5b-11e5-9ab5-94ff30de1f38.png">

**Comment by oblador** [comment]
Awesome! Is that chart a commit history graph or downloads graph? Anyway for that graph to be useful, it should probably have the same y-axis for all projects to be able to compare them. Also for clarity maybe it should be installs/month? Weekly installs is pretty volatile and will skew towards very recently updated projects, monthly is better IMHO.

**Comment by dmfrancisco** [comment]
Thanks! It's a downloads graph (I need to make that more obvious). The problem with using the same scale for all packages is that some will always be in a higher order of magnitude (for eg: a router library compared to an accordion). I suppose the scale could change based on the search results that are being displayed, but that makes things more complex. In my opinion, these are still useful because, like sparklines, they show a trend. And I'm using a sensible minimum for both axes (so that small changes don't look like a big deal).

You are right, the label should be "N installs in the last month" but it's quite big, so I'll use something like "N installs/mo" and show the more accurate description on hover.

Makes sense, regarding weekly vs monthly. Thank you for taking the time to share your feedback :+1:

**Comment by oblador** [comment]
More feedback then :-) : 
- I prefer the react.parts way of only coloring stats that stand out from the rest, ie many stars/downloads. 
- Some npm badges show the download rank of the package, ie "8th of xxx" or "top 15% of xxx". Might be useful?

**Comment by dmfrancisco** [comment]
1. Yes, I have to agree with you :smile: 
2. Do you happen to have a link for one of those? I've seen [global ranks](https://nodei.co/), but I don't remind seeing ranks per keyword.

**Comment by oblador** [comment]
re 2: that's what I meant :-) I guess it wouldn't be that hard to do an internal rank for the components on the site?

**Comment by dmfrancisco** [comment]
I guess you are right, it's an interesting idea. I'll play with it as soon as I get the time. Thanks again :+1:

**Comment by dmfrancisco** [comment]
Hello again @oblador, I addressed most of your feedback (monthly downloads instead of global, only coloring stats that stand out). The background install charts still need some love though.

There's a [new repo for feedback](https://github.com/dmfrancisco/JS.coach). Thanks again :+1:
