### ISSUE TITLE
Should I add component to react.parts if added it to js.coach ?

### ISSUE THREAD

**Issue by vitalets** [madebyform/react-parts#26]
If I should add it to both repos please add: [react-native-extended-stylesheet](https://github.com/vitalets/react-native-extended-stylesheet)

**Comment by dmfrancisco** [comment]
Hi @vitalets! No, the main reason we created the new site is because it's a lot easier to keep updated.

React.parts is still online because people are still using it. One of the reasons may be because search is better (React.parts uses Algolia, but the goal is to eventually start using it in JS.coach too).

Thank you for your contribution :+1:
